name: Deploy ARM64 Binary

on:
  workflow_run:
    workflows: ["Gordon-Proxy"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ARM64

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ github.event.workflow_run.conclusion == 'success' && matrix.goarch == 'arm64' && matrix.goos == 'linux' && steps.build.outputs.artifact_name }}

    - name: Deploy ARM64 Binary
      run: |
        tar xvf ${{ steps.download.outputs.artifacts }}/gordon-proxy-arm64-binary.tar.gz
        ./gordon-proxy-arm64-binary
